version: '2'
services:
    jhipster_demo_blog-app:
        image: jhipster_demo_blog
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster_demo_blog-postgresql:5432/jhipster_demo_blog
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_demo_blog-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster_demo_blog-postgresql
